export interface Project {
  id: number;
  title: string;
  description: string;
  featured: string;
  thumbnails: string[];
  link: string;
  category: string;
  duration?: number | string;
  aos?: string;
}

const normalizePath = (path: string) => {
  const decoded = decodeURIComponent(path);
  return decoded.startsWith('/') ? decoded : `/${decoded}`;
};

const toWebp = (path: string) => path.replace(/\.(png|PNG|jpe?g)$/i, '.webp');

const withPaths = (project: Project): Project => ({
  ...project,
  featured: toWebp(normalizePath(project.featured)),
  thumbnails: project.thumbnails.map((p) => toWebp(normalizePath(p))),
});

const rawProjects: Project[] = [
  {
    id: 13,
    title: "Akoya Deluxe Cleaning",
    description: "User-friendly, modern design showcasing top resources for managing overtime.",
    featured: "/project/lundary1.PNG",
    thumbnails: [
      "/project/lundary1.PNG",
      "/project/lundary2.PNG",
      "/project/lundary3.PNG",
      "/project/lundary4.PNG",
    ],
    link: "https://akoyaluxureylaundry.com/",
    aos: "fade-right",
    duration: 1000,
    category: "Website Development",
  },
  {
    id: 52,
    title: "Eduport   Education Course & LMS",
    description: "A modern education and learning management website designed for online courses, training centers, academies, schools, colleges and universities. The website features multiple course layouts, instructor and student dashboards, course details, pricing plans, admission forms, authentication pages, blogs and responsive educational interfaces. Built with Next.js and React for a fast and scalable learning platform experience.",
    featured: "/project/Eduport/edu1.png",
    thumbnails: [
      "/project/Eduport/edu1.png",
      "/project/Eduport/edu2.png",
      "/project/Eduport/edu3.png",
      "/project/Eduport/edu4.png",
    ],
    link: "https://themeforest.net/item/eduport-nextjs-education-course-and-lms-template/55294468",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 22,
    title: "Link Way Rides Platform",
    description: "A streamlined ride-booking website that connects users with reliable drivers, enhances bookings and ride management.",
    featured: "/project/car-rental/home.png",
    thumbnails: [
      "/project/car-rental/home.png",
      "/project/car-rental/service.png",
      "/project/car-rental/about.png",
      "/project/car-rental/contact.png",
    ],
    link: "https://linkwayrides.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 21,
    title: "Tamakon Comprehensive School",
    description: "Tamakon School offers specialized education and rehabilitation for students with diverse abilities across all academic levels.",
    featured: "/project/tamakon/home.png",
    thumbnails: [
      "/project/tamakon/home.png",
      "/project/tamakon/partner.png",
      "/project/tamakon/contact.png",
      "/project/tamakon/tamakon.png",
    ],
    link: "https://tamakon.in/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 48,
    title: "Ferm Living  Accessories",
    description: "A modern e-commerce accessories collection featuring beautifully designed home décor, including mirrors, vases, plant pots, candle holders, candles, storage solutions, bags, baskets and wallpaper. The website combines a clean Scandinavian aesthetic with elegant product presentation and a smooth shopping experience.",
    featured: "/project/FermLiving/ferm1.png",
    thumbnails: [
      "/project/FermLiving/ferm1.png",
      "/project/FermLiving/ferm2.png",
      "/project/FermLiving/ferm3.png",
      "/project/FermLiving/ferm4.png",
    ],
    link: "https://fermliving.com/collections/accessories",
    aos: "fade-left",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 23,
    title: "Al-Hafiz Online Quran Academy",
    description: "Al-Hafiz offers personalized one-on-one Quran and Tajweed lessons online for all ages, helping learners memorize and understand the Quran with certified teachers.",
    featured: "/project/quranAcademy/home.png",
    thumbnails: [
      "/project/quranAcademy/home.png",
      "/project/quranAcademy/service.png",
      "/project/quranAcademy/journey.png",
      "/project/quranAcademy/contact.png",
    ],
    link: "https://a-hafiz.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 14,
    title: "Empower Zone",
    description: "Empower Zone is a community-focused organization dedicated to helping New Yorkers access essential government benefits with ease",
    featured: "/project/empowerzone1.PNG",
    thumbnails: [
      "/project/empowerzone1.PNG",
      "/project/empowerzone2.PNG",
      "/project/empowerzone3.PNG",
      "/project/empowerzone4.PNG",
    ],
    link: "https://empowerzone.us",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 1,
    title: "Multi-Service Creative Agency",
    description: "A fully responsive online store with cart, payment gateway, and admin panel.",
    featured: "/project/novieta1.png",
    thumbnails: [
      "/project/novieta1.png",
      "/project/novieta2.png",
      "/project/novieta3.png",
      "/project/novieta4.png",
    ],
    link: "https://novietaaplus.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 2,
    title: "Trend Car Care",
    description: "A fully responsive online store with cart, payment gateway, and admin panel.",
    featured: "/project/trend1.png",
    thumbnails: [
      "/project/trend1.png",
      "/project/trend2.png",
      "/project/trend3.png",
      "/project/trend4.png",
    ],
    link: "https://trendcarcare.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 3,
    title: "The Givers Consulting",
    description: "A versatile and forward-thinking company offering a comprehensive suite of services.",
    featured: "/project/thegiverconsulting1.PNG",
    thumbnails: [
      "/project/thegiverconsulting1.PNG",
      "/project/thegiverconsulting2.PNG",
      "/project/thegiverconsulting3.PNG",
      "/project/thegiverconsulting4.PNG",
    ],
    link: "https://thegiversconsulting.com",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 5,
    title: "Innovative Workforce Management Solutions",
    description: "Innovative Workforce Management Solutions streamline employee scheduling, attendance tracking, and productivity monitoring using advanced technologies.",
    featured: "/project/glidesk1.PNG",
    thumbnails: [
      "/project/glidesk1.PNG",
      "/project/glidesk2.PNG",
      "/project/glidesk3.PNG",
      "/project/glidesk4.PNG",
    ],
    link: "https://glidesk.com",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 6,
    title: "Softech Business Solutions",
    description: "Softech Business Solutions is a forward-thinking company specializing in delivering innovative software and technology services to businesses of all sizes.",
    featured: "/project/softech1.PNG",
    thumbnails: [
      "/project/softech1.PNG",
      "/project/softech2.PNG",
      "/project/softech3.PNG",
      "/project/softech4.PNG",
    ],
    link: "https://www.softechbusinessservices.com",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 7,
    title: "Nasa Teck Innovations It Services",
    description: "NASA Teck Innovations IT Services is a technology company based in Bahawalpur, Pakistan, operating under the name Sky Innovations IT Services L.L.C.",
    featured: "/project/nasateck1.PNG",
    thumbnails: [
      "/project/nasateck1.PNG",
      "/project/nasateck2.PNG",
      "/project/nasateck3.PNG",
      "/project/nasateck4.PNG",
    ],
    link: "https://nasateck.com",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 24,
    title: "Mobilia Consulting",
    description: "A professional corporate website for Mobilia Consulting, showcasing their data-driven approach to optimizing indirect spend, delivering measurable savings, and fostering sustainable business growth worldwide.",
    featured: "/project/mobila/home.png",
    thumbnails: [
      "/project/mobila/home.png",
      "/project/mobila/service.png",
      "/project/mobila/about.png",
      "/project/mobila/contact.png",
    ],
    link: "https://mobilia-consulting-pi.vercel.app/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 25,
    title: "AZ Enterprise",
    description: "A modern IT services website delivering tailored digital solutions, insightful tech blogs, and strategic guidance to help businesses achieve lasting digital growth.",
    featured: "/project/azInterprice/home.png",
    thumbnails: [
      "/project/azInterprice/home.png",
      "/project/azInterprice/service.png",
      "/project/azInterprice/about.png",
      "/project/azInterprice/contact.png",
    ],
    link: "https://az-enterprizednbhd.vercel.app/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 17,
    title: "Sports Tracker: Run Bike Hike",
    description: "The Ultimate Sports Tracking App for Outdoor Adventures and Fitness Improvement Track your running, cycling, hiking, and over 90 other sports with precision and ease.",
    featured: "/project/sports1.png",
    thumbnails: [
      "/project/sports1.png",
      "/project/sports2.png",
      "/project/sports3.png",
      "/project/sports4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.stt.android&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 18,
    title: "SuperSports",
    description: "Welcome to the SuperSport app experience your personalised sports companion.It is the perfect supplement to your World of Champions unrivaled broadcast coverage of the best in world sport, and is designed to give you just what you want, when you want it.",
    featured: "/project/super3.png",
    thumbnails: [
      "/project/super3.png",
      "/project/super2.png",
      "/project/super1.png",
      "/project/super4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.supersport.android.phone&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 19,
    title: "Get Gaari - Rental Car Sharing",
    description: "Get Gaari is your ultimate car rental solution, connecting car owners with renters in a convenient and secure platform. Whether you need a car for a day, a week, or longer, Get Gaari makes the process quick and easy.",
    featured: "/project/get1.png",
    thumbnails: [
      "/project/get1.png",
      "/project/get2.png",
      "/project/get3.png",
      "/project/get4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.roboart.getgaari&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 26,
    title: "Pure Fitness Africa Mobile App",
    description: "Join the most exciting fitness community in Africa and embark on your fitness journey with the Pure Fitness Africa all-in-one mobile app.",
    featured: "/project/pure1.png",
    thumbnails: [
      "/project/pure1.png",
      "/project/pure2.png",
      "/project/pure3.png",
      "/project/pure4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.initsng.purefitnessafrica4&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 27,
    title: "Qatar Sale",
    description: "QatarSale is the first and biggest on-line (web / app) cars and motorbikes trading in QATAR",
    featured: "/project/qatar1.png",
    thumbnails: [
      "/project/qatar1.png",
      "/project/qatar2.png",
      "/project/qatar3.png",
      "/project/qatar4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.qatarsale&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 28,
    title: "SnapScan",
    description: "Payments shouldn't disrupt the joy of simple pleasures. Whether you're on the go or on the couch, SnapScan allows you to r quick and easy payments.",
    featured: "/project/snap1.png",
    thumbnails: [
      "/project/snap1.png",
      "/project/snap2.png",
      "/project/snap3.png",
      "/project/snap4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.fireid.snapscan&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 29,
    title: "Weather You",
    description: "WeatherYou is your personal and modern weather companion. Effortlessly check current conditions and forecasts on your phone, tablet/foldable, TV, or wearable.",
    featured: "/project/wheather1.png",
    thumbnails: [
      "/project/wheather1.png",
      "/project/wheather2.png",
      "/project/wheather3.png",
      "/project/wheather4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.rodrigmatrix.weatheryou&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 30,
    title: "ARABIAN DUNES TOURS",
    description: "Arabian Dunes Tours is the most trusted and quickest source for booking desert safari Dubai in the United Arab Emirates. We offer full-service packages for different kinds of safaris in Dubai to fill your life with desert adventure.",
    featured: "/project/dunes1.png",
    thumbnails: [
      "/project/dunes1.png",
      "/project/dunes2.png",
      "/project/dunes3.png",
      "/project/dunes4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 31,
    title: "Best Arabic Coffee Server in Dubai & UAE",
    description: "Book your Dubai event with our expert coffee servers. Enjoy flawless coffee service, tailored to perfection. Impress your guests with barista-crafted beverages.",
    featured: "/project/coffe1.png",
    thumbnails: [
      "/project/coffe1.png",
      "/project/coffe2.png",
      "/project/coffe3.png",
      "/project/coffe4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 33,
    title: "ARABIAN Dune Buggy",
    description: "Experience the thrill of Dubai's golden dunes like never before with Arabian Dune Buggy! We specialize in offering private and exclusive dune buggy tours that promise to make your Dubai adventure unforgettable.",
    featured: "/project/arabic1.png",
    thumbnails: [
      "/project/arabic1.png",
      "/project/arabic2.png",
      "/project/arabic3.png",
      "/project/arabic4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 34,
    title: "Specialist Laser Aesthetics Based In Dagenham",
    description: "We are proud to be a 5 Star NHS Approved Clinic and we are the only clinic in East London offering treatments using the Quanta Thunder Series.",
    featured: "/project/laser1.png",
    thumbnails: [
      "/project/laser1.png",
      "/project/laser2.png",
      "/project/laser3.png",
      "/project/laser4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 37,
    title: "Welcome to Progen Aesthetics Clinic",
    description: "Doctor and nurse led aesthetic clinic which utilizes the latest technology in health and beauty for a natural and balanced transformation.",
    featured: "/project/progen1.png",
    thumbnails: [
      "/project/progen1.png",
      "/project/progen2.png",
      "/project/progen3.png",
      "/project/progen4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 39,
    title: "ARABIAN LUXURY TOURS",
    description: "Embark on a once-in-a-lifetime adventure with our luxury desert safari tour packages in Dubai. Immerse yourself in the breathtaking beauty of the desert landscape while enjoying the finest amenities and unparalleled service.",
    featured: "/project/tour1.png",
    thumbnails: [
      "/project/tour1.png",
      "/project/tour2.png",
      "/project/tour3.png",
      "/project/tour4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 41,
    title: "Best Freelancing Academy in Pakistan",
    description: "Axcore Training Academy is forefront provider of professional education to all those who want to learn and grow. Our Academy is located in Karachi, Pakistan.",
    featured: "/project/best1.png",
    thumbnails: [
      "/project/best1.png",
      "/project/best2.png",
      "/project/best3.png",
      "/project/best4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 43,
    title: "Welcome to Learn Driving UK",
    description: "We're dedicated to helping you become a confident and skilled driver. Our family-run driving school offers personalised lessons tailored to suit your needs, with experienced instructors who guide you every step of the way.",
    featured: "/project/learing1.png",
    thumbnails: [
      "/project/learing1.png",
      "/project/learing2.png",
      "/project/learing3.png",
      "/project/learing4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 45,
    title: "Mini Digger & Driver Hire",
    description: "Gardenology is a groundworks company based in south Bristol, covering the Bristol, Swindon, Bath, Mendips, Weston-super-Mare and Cardiff areas.",
    featured: "/project/mini1.png",
    thumbnails: [
      "/project/mini1.png",
      "/project/mini2.png",
      "/project/mini3.png",
      "/project/mini4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 46,
    title: "No Loss Daily Savings",
    description: "Gardenology is a groundworks company based in south Bristol, covering the Bristol, Swindon, Bath, Mendips, Weston-super-Mare and Cardiff areas.",
    featured: "/project/yestime/yes1.png",
    thumbnails: [
      "/project/yestime/yes1.png",
      "/project/yestime/yes2.png",
      "/project/yestime/yes3.png",
      "/project/yestime/yes4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 47,
    title: "Expert Care for Your Washing Machine",
    description: "Gardenology is a groundworks company based in south Bristol, covering the Bristol, Swindon, Bath, Mendips, Weston-super-Mare and Cardiff areas.",
    featured: "/project/FridgeRepair/frg1.png",
    thumbnails: [
      "/project/FridgeRepair/frg1.png",
      "/project/FridgeRepair/frg2.png",
      "/project/FridgeRepair/frg3.png",
      "/project/FridgeRepair/frg4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 55,
    title: "Turo",
    description: "Turo is a peer-to-peer car sharing marketplace where people can book cars from local hosts.",
    featured: "/project/Turo/turo1.png",
    thumbnails: [
      "/project/Turo/turo1.png",
      "/project/Turo/turo2.png",
      "/project/Turo/turo3.png",
      "/project/Turo/turo4.png",
    ],
    link: "https://turo.com",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 56,
    title: "Bagallery",
    description: "Bagallery is an online beauty and lifestyle store offering a wide range of cosmetics, skincare, fragrances, personal care, and beauty products.",
    featured: "/project/Bagallery/bag1.png",
    thumbnails: [
      "/project/Bagallery/bag1.png",
      "/project/Bagallery/bag2.png",
      "/project/Bagallery/bag3.png",
      "/project/Bagallery/bag4.png",
    ],
    link: "https://bagallery.com/",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 57,
    title: "Clicky",
    description: "Clicky is a professional online platform designed to provide modern digital products and services with a clean and user-friendly experience.",
    featured: "/project/Clicky/clicky1.png",
    thumbnails: [
      "/project/Clicky/clicky1.png",
      "/project/Clicky/clicky2.png",
      "/project/Clicky/clicky3.png",
      "/project/Clicky/clicky4.png",
    ],
    link: "https://www.clicky.pk/",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 58,
    title: "Al-Fatah",
    description: "Al-Fatah is a leading online shopping store in Pakistan, offering a wide range of groceries, household essentials, beauty products, electronics, and lifestyle products.",
    featured: "/project/Al-Fatah/alfatah1.png",
    thumbnails: [
      "/project/Al-Fatah/alfatah1.png",
      "/project/Al-Fatah/alfatah2.png",
      "/project/Al-Fatah/alfatah3.png",
      "/project/Al-Fatah/alfatah4.png",
    ],
    link: "https://alfatah.pk/",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 59,
    title: "Export Leftovers",
    description: "Export Leftovers is an online fashion and clothing store offering a wide range of apparel and lifestyle products.",
    featured: "/project/Export Leftovers/export1.png",
    thumbnails: [
      "/project/Export Leftovers/export1.png",
      "/project/Export Leftovers/export2.png",
      "/project/Export Leftovers/export3.png",
      "/project/Export Leftovers/export4.png",
    ],
    link: "https://www.exportleftovers.com/",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 60,
    title: "WBM Mart",
    description: "WBM Mart is an online e-commerce store offering a wide range of household, beauty, baby care, electronics, grocery, and daily essential products.",
    featured: "/project/WBM/wbm1.png",
    thumbnails: [
      "/project/WBM/wbm1.png",
      "/project/WBM/wbm2.png",
      "/project/WBM/wbm3.png",
      "/project/WBM/wbm4.png",
    ],
    link: "https://wbm.com.pk/",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 61,
    title: "High Street Pakistan",
    description: "High Street Pakistan is a luxury e-commerce store offering authentic fashion, beauty, skincare, bags, fragrances, makeup, and premium lifestyle products.",
    featured: "/project/HighStreet/highstreet1.png",
    thumbnails: [
      "/project/HighStreet/highstreet1.png",
      "/project/HighStreet/highstreet2.png",
      "/project/HighStreet/highstreet3.png",
      "/project/HighStreet/highstreet4.png",
    ],
    link: "https://highstreetpakistan.co/",
    aos: "fade-right",
    duration: "1000",
    category: "WordPress",
  },
  {
    id: 49,
    title: "Vista Restaurant & Food Menu",
    description: "A modern restaurant website featuring a beautifully organized digital food menu with categories, food items, prices and detailed menu presentation. The website provides a clean and user-friendly experience for customers to explore restaurant offerings and discover different food options through an attractive and responsive interface.",
    featured: "/project/VistaRestaurant/vista1.png",
    thumbnails: [
      "/project/VistaRestaurant/vista1.png",
      "/project/VistaRestaurant/vista2.png",
      "/project/VistaRestaurant/vista3.png",
      "/project/VistaRestaurant/vista4.png",
    ],
    link: "https://vista.menuhoster.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 50,
    title: "Care – Beauty & Cosmetics Store",
    description: "A modern beauty and cosmetics e-commerce website featuring a clean product-focused layout with skincare, beauty and personal care products. The website includes product categories, product listings, prices, shopping features and a responsive interface designed to provide a smooth and attractive online shopping experience.",
    featured: "/project/CareCosmetics/care1.png",
    thumbnails: [
      "/project/CareCosmetics/care1.png",
      "/project/CareCosmetics/care2.png",
      "/project/CareCosmetics/care3.png",
      "/project/CareCosmetics/care4.png",
    ],
    link: "https://demo.templatesjungle.com/care/shop-sidebar.html",
    aos: "fade-left",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 51,
    title: "Fitzone – Gym & Fitness",
    description: "A modern gym and fitness website designed to showcase workout programs, fitness classes, membership plans and professional training services. The website features an engaging hero section, fitness programs, pricing plans, testimonials and a responsive layout that provides an attractive and user-friendly experience for gym members.",
    featured: "/project/Fitzone/fit1.png",
    thumbnails: [
      "/project/Fitzone/fit1.png",
      "/project/Fitzone/fit2.png",
      "/project/Fitzone/fit3.png",
      "/project/Fitzone/fit4.png",
    ],
    link: "https://demo.templatesjungle.com/fitzone/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 53,
    title: "HealthPoint – Advanced Healthcare",
    description: "A modern healthcare and medical website designed to provide personalized healthcare services and an easy patient experience. The website features medical services, doctor profiles, appointment booking, emergency support, mental health support, customer testimonials, medical blogs and multiple healthcare departments including cardiology, radiology, gynecology, eye care and sports injury services. It provides a professional, responsive and user-friendly interface for patients to explore healthcare services and connect with doctors.",
    featured: "/project/HealthPoint/health1.png",
    thumbnails: [
      "/project/HealthPoint/health1.png",
      "/project/HealthPoint/health2.png",
      "/project/HealthPoint/health3.png",
      "/project/HealthPoint/health4.png",
    ],
    link: "https://health-point-nextjs-pro.vercel.app/",
    aos: "fade-left",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 54,
    title: "Renix Care – Onlino Pharmacy",
    description: "A modern online pharmacy and healthcare e-commerce website designed to make medicines, healthcare products and wellness essentials easily accessible. The website features product categories, medicine listings, combo offers, product details, doctor consultation, online ordering, delivery services and a user-friendly shopping experience. Its responsive interface provides a professional and convenient platform for customers to explore healthcare products and place orders online.",
    featured: "/project/RenixCare/renix1.png",
    thumbnails: [
      "/project/RenixCare/renix1.png",
      "/project/RenixCare/renix2.png",
      "/project/RenixCare/renix3.png",
      "/project/RenixCare/renix4.png",
    ],
    link: "https://nextrestart.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 64,
    title: "Turbo – Car Wash",
    description: "A modern car wash and vehicle care website designed to provide professional car cleaning services with an attractive and user-friendly interface. The website features car wash services, online booking, inspection, valuation, service packages, pricing plans, project gallery, customer-focused information and car care tips. It offers a responsive and engaging platform for customers to explore wash packages and book professional car cleaning services.",
    featured: "/project/TurboCarWash/turbo1.png",
    thumbnails: [
      "/project/TurboCarWash/turbo1.png",
      "/project/TurboCarWash/turbo2.png",
      "/project/TurboCarWash/turbo3.png",
      "/project/TurboCarWash/turbo4.png",
    ],
    link: "https://demo.templatesjungle.com/turbo/",
    aos: "fade-right",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 66,
    title: "GadgetHub – Electronics eCommerce",
    description: "A modern electronics e-commerce website designed for showcasing and selling gadgets, accessories and technology products. The website features product listings, shopping cart, checkout, responsive layouts and a clean user-friendly interface. Its modern design provides an attractive online shopping experience for customers looking for electronic products and accessories.",
    featured: "/project/GadgetHub/gadget1.png",
    thumbnails: [
      "/project/GadgetHub/gadget1.png",
      "/project/GadgetHub/gadget2.png",
      "/project/GadgetHub/gadget3.png",
      "/project/GadgetHub/gadget4.png",
    ],
    link: "https://demo.templatesjungle.com/gadgethub/",
    aos: "fade-left",
    duration: "1000",
    category: "Website Development",
  },
  {
    id: 67,
    title: "SwiftShip – Logistics & Delivery App",
    description: "A modern logistics and delivery mobile app designed to streamline shipment management, real-time delivery tracking, rider operations, and customer order management.",
    featured: "/project/SwiftShip/Swiftapp1.png",
    thumbnails: [
      "/project/SwiftShip/Swiftapp1.png",
      "/project/SwiftShip/Swiftapp2.png",
      "/project/SwiftShip/Swiftapp3.png",
      "/project/SwiftShip/Swiftapp4.png",
    ],
    link: "https://www.rapidnative.com/pricing",
    aos: "fade-right",
    duration: 1000,
    category: "App",
  },
  {
    id: 100,
    title: "Telegram",
    description: "A fast and secure messaging app offering private conversations, group chats, channels, media sharing, voice communication, and online communities.",
    featured: "/project/SwiftShip/Telegram1.png",
    thumbnails: [
      "/project/SwiftShip/Telegram1.png",
      "/project/SwiftShip/Telegram2.png",
      "/project/SwiftShip/Telegram3.png",
      "/project/SwiftShip/Telegram4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=en",
    aos: "fade-up",
    duration: "1000",
    category: "App",
  },
  {
    id: 101,
    title: "Discord",
    description: "A community and communication app designed for messaging, voice and video conversations, gaming communities, file sharing, and real-time collaboration.",
    featured: "/project/SwiftShip/discord1.png",
    thumbnails: [
      "/project/SwiftShip/discord1.png",
      "/project/SwiftShip/discord2.png",
      "/project/SwiftShip/discord3.png",
      "/project/SwiftShip/discord4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.discord&hl=en",
    aos: "fade-left",
    duration: "1000",
    category: "App",
  },
  {
    id: 102,
    title: "Slack",
    description: "A professional workplace communication app that helps teams collaborate through organized channels, direct messaging, file sharing, and project communication.",
    featured: "/project/SwiftShip/slack1.png",
    thumbnails: [
      "/project/SwiftShip/slack1.png",
      "/project/SwiftShip/slack2.png",
      "/project/SwiftShip/slack3.png",
      "/project/SwiftShip/slack4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.Slack&hl=en",
    aos: "fade-up",
    duration: "1000",
    category: "App",
  },
  {
    id: 103,
    title: "Zoom",
    description: "A professional video communication app that enables users to host and join virtual meetings, make video calls, share screens, collaborate with teams, and attend online events.",
    featured: "/project/SwiftShip/zoom1.png",
    thumbnails: [
      "/project/SwiftShip/zoom1.png",
      "/project/SwiftShip/zoom2.png",
      "/project/SwiftShip/zoom3.png",
      "/project/SwiftShip/zoom4.png",
    ],
    link: "https://play.google.com/store/search?q=zoom&c=apps",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 104,
    title: "TaskRabbit – Local Services App",
    description: "A convenient service marketplace app that connects users with trusted local professionals for home repairs, cleaning, moving, delivery, and everyday tasks.",
    featured: "/project/SwiftShip/taskrabbit1.png",
    thumbnails: [
      "/project/SwiftShip/taskrabbit1.png",
      "/project/SwiftShip/taskrabbit2.png",
      "/project/SwiftShip/taskrabbit3.png",
      "/project/SwiftShip/taskrabbit4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.taskrabbit.droid.consumer&hl=en",
    aos: "fade-left",
    duration: "1000",
    category: "App",
  },
  {
    id: 105,
    title: "Too Good To Go – Food Saving App",
    description: "A sustainability-focused food marketplace app that connects users with local restaurants, cafes, and stores to discover quality surplus food at affordable prices.",
    featured: "/project/SwiftShip/toogoodtogo1.png",
    thumbnails: [
      "/project/SwiftShip/toogoodtogo1.png",
      "/project/SwiftShip/toogoodtogo2.png",
      "/project/SwiftShip/toogoodtogo3.png",
      "/project/SwiftShip/toogoodtogo4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.app.tgtg&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 106,
    title: "Komoot – Outdoor Navigation App",
    description: "An outdoor navigation app designed for hiking, cycling, and running, offering route planning, detailed maps, turn-by-turn navigation, and personalized adventure recommendations.",
    featured: "/project/SwiftShip/komoot1.png",
    thumbnails: [
      "/project/SwiftShip/komoot1.png",
      "/project/SwiftShip/komoot2.png",
      "/project/SwiftShip/komoot3.png",
      "/project/SwiftShip/komoot4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=de.komoot.android&hl=en",
    aos: "fade-up",
    duration: "1000",
    category: "App",
  },
  {
    id: 107,
    title: "Lime – Urban Mobility App",
    description: "A smart urban mobility app that helps users find and unlock nearby electric scooters and bikes, plan short trips, and navigate cities with convenient shared transportation.",
    featured: "/project/SwiftShip/lime1.png",
    thumbnails: [
      "/project/SwiftShip/lime1.png",
      "/project/SwiftShip/lime2.png",
      "/project/SwiftShip/lime3.png",
      "/project/SwiftShip/lime4.png",
    ],
    link: "https://play.google.com/store/apps/details/Lime_RideGreen?id=com.limebike&hl=en_ZA",
    aos: "fade-left",
    duration: "1000",
    category: "App",
  },
  {
    id: 62,
    title: "Blinkist – Book Summary App",
    description: "A knowledge and learning app that provides concise book summaries, key insights, and audio content to help users discover and learn from bestselling nonfiction books.",
    featured: "/project/SwiftShip/bankist1.png",
    thumbnails: [
      "/project/SwiftShip/bankist1.png",
      "/project/SwiftShip/bankist2.png",
      "/project/SwiftShip/bankist3.png",
      "/project/SwiftShip/bankist4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=com.blinkslabs.blinkist.android&hl=en",
    aos: "fade-right",
    duration: "1000",
    category: "App",
  },
  {
    id: 108,
    title: "Forest – Focus & Productivity App",
    description: "A minimalist productivity app that helps users stay focused by growing virtual trees while they work, reducing distractions, building healthy habits, and tracking focused time.",
    featured: "/project/SwiftShip/forest1.png",
    thumbnails: [
      "/project/SwiftShip/forest1.png",
      "/project/SwiftShip/forest2.png",
      "/project/SwiftShip/forest3.png",
      "/project/SwiftShip/forest4.png",
    ],
    link: "https://play.google.com/store/apps/details?id=cc.forestapp&hl=en",
    aos: "fade-left",
    duration: "1000",
    category: "App",
  },
  {
    id: 109,
    title: "Mokobara",
    description: "A premium Shopify e-commerce experience for modern travel and lifestyle products, presented through a clean, product-focused interface.",
    featured: "/project/Mokobara/mokobara1.png",
    thumbnails: [
      "/project/Mokobara/mokobara1.png",
      "/project/Mokobara/mokobara2.png",
      "/project/Mokobara/mokobara3.png",
      "/project/Mokobara/mokobara4.png",
    ],
    link: "https://mokobara.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 68,
    title: "Dermalogica",
    description: "A polished Shopify storefront for professional skincare products, combining editorial content, product discovery and a refined shopping experience.",
    featured: "/project/Dermalogica/dermalogica1.png",
    thumbnails: [
      "/project/Dermalogica/dermalogica1.png",
      "/project/Dermalogica/dermalogica2.png",
      "/project/Dermalogica/dermalogica3.png",
      "/project/Dermalogica/dermalogica4.png",
    ],
    link: "https://www.dermalogica.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 69,
    title: "Polywood",
    description: "A modern Shopify commerce experience for outdoor furniture, designed to showcase products, collections and lifestyle imagery clearly.",
    featured: "/project/Polywood/polywood1.png",
    thumbnails: [
      "/project/Polywood/polywood1.png",
      "/project/Polywood/polywood2.png",
      "/project/Polywood/polywood3.png",
      "/project/Polywood/polywood4.png",
    ],
    link: "https://www.polywood.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 70,
    title: "Armedangels",
    description: "A fashion-focused Shopify storefront with a contemporary visual system for presenting sustainable apparel, collections and product details.",
    featured: "/project/Armedangels/armedangels1.png",
    thumbnails: [
      "/project/Armedangels/armedangels1.png",
      "/project/Armedangels/armedangels2.png",
      "/project/Armedangels/armedangels3.png",
      "/project/Armedangels/armedangels4.png",
    ],
    link: "https://www.armedangels.com/?from_logo=1",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 71,
    title: "Brunt Workwear",
    description: "A rugged Shopify e-commerce experience for workwear, built to highlight product collections, utility and a straightforward shopping journey.",
    featured: "/project/BruntWorkwear/brunt1.png",
    thumbnails: [
      "/project/BruntWorkwear/brunt1.png",
      "/project/BruntWorkwear/brunt2.png",
      "/project/BruntWorkwear/brunt3.png",
      "/project/BruntWorkwear/brunt4.png",
    ],
    link: "https://bruntworkwear.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 72,
    title: "Allbirds",
    description: "A minimalist Shopify storefront for footwear and apparel, using clear product presentation and a simple, accessible retail experience.",
    featured: "/project/Allbirds/allbirds1.png",
    thumbnails: [
      "/project/Allbirds/allbirds1.png",
      "/project/Allbirds/allbirds2.png",
      "/project/Allbirds/allbirds3.png",
      "/project/Allbirds/allbirds4.png",
    ],
    link: "https://www.allbirds.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 73,
    title: "Kith",
    description: "A fashion and lifestyle Shopify experience designed around strong visual merchandising, collections and premium product discovery.",
    featured: "/project/Kith/kith1.png",
    thumbnails: [
      "/project/Kith/kith1.png",
      "/project/Kith/kith2.png",
      "/project/Kith/kith3.png",
      "/project/Kith/kith4.png",
    ],
    link: "https://kith.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 74,
    title: "Heinz",
    description: "A branded Shopify commerce experience for a globally recognized food brand, combining product storytelling with clear retail pathways.",
    featured: "/project/Heinz/heinz1.png",
    thumbnails: [
      "/project/Heinz/heinz1.png",
      "/project/Heinz/heinz2.png",
      "/project/Heinz/heinz3.png",
      "/project/Heinz/heinz4.png",
    ],
    link: "https://www.heinz.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 75,
    title: "Quad Lock Case",
    description: "A product-led Shopify storefront for mobile accessories, presenting technical features, compatibility and products in a clear buying journey.",
    featured: "/project/QuadlockCase/quadlock1.png",
    thumbnails: [
      "/project/QuadlockCase/quadlock1.png",
      "/project/QuadlockCase/quadlock2.png",
      "/project/QuadlockCase/quadlock3.png",
      "/project/QuadlockCase/quadlock4.png",
    ],
    link: "https://www.quadlockcase.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 76,
    title: "Tentree",
    description: "A sustainable fashion Shopify storefront designed to present eco-conscious apparel, collections and products through a clean shopping experience.",
    featured: "/project/Tentree/tentree1.png",
    thumbnails: [
      "/project/Tentree/tentree1.png",
      "/project/Tentree/tentree2.png",
      "/project/Tentree/tentree3.png",
      "/project/Tentree/tentree4.png",
    ],
    link: "https://www.tentree.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 77,
    title: "MR MARVIS",
    description: "A refined Shopify fashion storefront focused on premium everyday clothing, product discovery and an engaging retail journey.",
    featured: "/project/MRMarvis/mrmarvis1.png",
    thumbnails: [
      "/project/MRMarvis/mrmarvis1.png",
      "/project/MRMarvis/mrmarvis2.png",
      "/project/MRMarvis/mrmarvis3.png",
      "/project/MRMarvis/mrmarvis4.png",
    ],
    link: "https://www.mrmarvis.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 78,
    title: "Scuffers",
    description: "A contemporary Shopify streetwear experience built around bold visual merchandising, apparel collections and product-led browsing.",
    featured: "/project/Scuffers/scuffers1.png",
    thumbnails: [
      "/project/Scuffers/scuffers1.png",
      "/project/Scuffers/scuffers2.png",
      "/project/Scuffers/scuffers3.png",
      "/project/Scuffers/scuffers4.png",
    ],
    link: "https://scuffers.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 79,
    title: "Caden Lane",
    description: "A welcoming Shopify e-commerce experience for baby and family products, combining lifestyle imagery with clear product discovery.",
    featured: "/project/CadenLane/cadenlane1.png",
    thumbnails: [
      "/project/CadenLane/cadenlane1.png",
      "/project/CadenLane/cadenlane2.png",
      "/project/CadenLane/cadenlane3.png",
      "/project/CadenLane/cadenlane4.png",
    ],
    link: "https://cadenlane.com/en-mx",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 80,
    title: "Made by Mary",
    description: "A polished Shopify jewelry storefront that presents personalized products, collections and gifting options in an elegant shopping experience.",
    featured: "/project/MadeByMary/madebymary1.png",
    thumbnails: [
      "/project/MadeByMary/madebymary1.png",
      "/project/MadeByMary/madebymary2.png",
      "/project/MadeByMary/madebymary3.png",
      "/project/MadeByMary/madebymary4.png",
    ],
    link: "https://madebymary.com/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  {
    id: 81,
    title: "Wildling Shoes",
    description: "A distinctive Shopify footwear experience focused on natural materials, product storytelling and an intuitive path to purchase.",
    featured: "/project/WildlingShoes/wildling1.png",
    thumbnails: [
      "/project/WildlingShoes/wildling1.png",
      "/project/WildlingShoes/wildling2.png",
      "/project/WildlingShoes/wildling3.png",
      "/project/WildlingShoes/wildling4.png",
    ],
    link: "https://www.wildling.shoes/",
    aos: "fade-right",
    duration: "1000",
    category: "Shopify",
  },
  // ── UI/UX Design ──
  {
    id: 82,
    title: "Figma Design Luxury Laundry",
    description:
      "Sleek, data-driven UI design for a luxury laundry app with interactive flows, booking screens, and real-time order tracking.",
    featured: "/project/LundaryApp.png",
    thumbnails: [
      "/project/LundaryApp.png",
      "/project/lundaryone.png",
      "/project/lundarytwo.png",
      "/project/lundarythree.png",
    ],
    link: "https://www.figma.com/design/Yh9j7PkNLuq4ltbjsxGnve/Laundry-app?node-id=0-1&p=f&t=2ooOSeIPRuCxZlhL-0",
    aos: "fade-right",
    duration: "1000",
    category: "UI/UX",
  },
  {
    id: 83,
    title: "Figma Design Transpohub & Logistics",
    description:
      "Modern logistics UI showcasing Transpohub's delivery solutions with clear service highlights, dashboards, and responsive layouts.",
    featured: "/project/logistic1.PNG",
    thumbnails: [
      "/project/logistic1.PNG",
      "/project/logistic2.PNG",
      "/project/logistic3.PNG",
      "/project/logistic4.PNG",
    ],
    link: "https://www.figma.com/design/Av2Ed3J1tlnSo8JA2D1PjR/Logistics?node-id=0-1&p=f&t=IKTHkquXNld8K9xj-0",
    aos: "fade-right",
    duration: "1000",
    category: "UI/UX",
  },
  {
    id: 84,
    title: "Figma Design Deckohost",
    description:
      "Clean and professional hosting service UI with intuitive navigation, pricing plans, and feature-focused landing pages.",
    featured: "/project/deckohost1.PNG",
    thumbnails: [
      "/project/deckohost1.PNG",
      "/project/deckohost2.PNG",
      "/project/deckohost3.PNG",
      "/project/deckohost4.PNG",
    ],
    link: "https://www.figma.com/design/kq0atK4yTRCbNkm7KJlZiG/Dekohost?node-id=0-1&p=f&t=1LyabYSTl3Tx66L7-0",
    aos: "fade-right",
    duration: "1000",
    category: "UI/UX",
  },
  {
    id: 85,
    title: "Figma Design SkillSphere – Exam Prep",
    description:
      "User-friendly modern design showcasing top resources for competitive exam preparation and structured learning paths.",
    featured: "/project/ppsc1.PNG",
    thumbnails: [
      "/project/ppsc1.PNG",
      "/project/ppsc2.PNG",
      "/project/ppsc3.PNG",
      "/project/ppsc4.PNG",
    ],
    link: "https://www.figma.com/design/kvDU7sk6epN4m7H2lXYYkU/SkillSphere?node-id=0-1&p=f&t=rrBbr1V8j5Ge3SPQ-0",
    aos: "fade-right",
    duration: "1000",
    category: "UI/UX",
  },
  {
    id: 86,
    title: "Overtime Management UI",
    description:
      "Modern workforce UI for tracking overtime hours, approvals, and employee scheduling with a clean dashboard experience.",
    featured: "/project/overtime1.jpg",
    thumbnails: [
      "/project/overtime1.jpg",
      "/project/overtime2.jpg",
      "/project/overtime3.jpg",
      "/project/overtime4.jpg",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "UI/UX",
  },
  {
    id: 87,
    title: "Figma AI Interface Design",
    description:
      "AI-powered product UI design featuring smart assistants, conversational flows, and polished interaction patterns.",
    featured: "/project/figmaAi1.png",
    thumbnails: [
      "/project/figmaAi1.png",
      "/project/figmaAi2.png",
      "/project/figmaAi3.png",
      "/project/figmaAi4.png",
    ],
    link: "#",
    aos: "fade-left",
    duration: "1000",
    category: "UI/UX",
  },
  // ── SEO Projects ──
  {
    id: 120,
    title: "ARABIAN DUNES TOURS",
    description:
      "SEO-optimized desert safari website ranking for Dubai adventure and desert tour keywords with structured content and fast performance.",
    featured: "/project/dunes1.png",
    thumbnails: [
      "/project/dunes1.png",
      "/project/dunes2.png",
      "/project/dunes3.png",
      "/project/dunes4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
  {
    id: 121,
    title: "Best Arabic Coffee Server in Dubai & UAE",
    description:
      "Search-optimized landing experience for Arabic coffee catering services targeting event and hospitality keywords in the UAE.",
    featured: "/project/coffe1.png",
    thumbnails: [
      "/project/coffe1.png",
      "/project/coffe2.png",
      "/project/coffe3.png",
      "/project/coffe4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
  {
    id: 122,
    title: "ARABIAN Dune Buggy",
    description:
      "SEO-driven dune buggy tour website built to rank for Dubai adventure, desert safari, and off-road experience searches.",
    featured: "/project/arabic1.png",
    thumbnails: [
      "/project/arabic1.png",
      "/project/arabic2.png",
      "/project/arabic3.png",
      "/project/arabic4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
  {
    id: 123,
    title: "Specialist Laser Aesthetics Based In Dagenham",
    description:
      "Local SEO optimized clinic website targeting laser treatment and aesthetic service keywords across East London.",
    featured: "/project/laser1.png",
    thumbnails: [
      "/project/laser1.png",
      "/project/laser2.png",
      "/project/laser3.png",
      "/project/laser4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
  {
    id: 124,
    title: "Welcome to Progen Aesthetics Clinic",
    description:
      "SEO-focused aesthetic clinic website optimized for health and beauty treatment searches with strong on-page structure.",
    featured: "/project/progen1.png",
    thumbnails: [
      "/project/progen1.png",
      "/project/progen2.png",
      "/project/progen3.png",
      "/project/progen4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
  {
    id: 125,
    title: "ARABIAN LUXURY TOURS",
    description:
      "Luxury desert safari SEO campaign with keyword-targeted pages, meta optimization, and content built for high-intent travel searches.",
    featured: "/project/tour1.png",
    thumbnails: [
      "/project/tour1.png",
      "/project/tour2.png",
      "/project/tour3.png",
      "/project/tour4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
  {
    id: 126,
    title: "Best Freelancing Academy in Pakistan",
    description:
      "SEO-optimized education website targeting freelancing, digital skills, and training course keywords in Pakistan.",
    featured: "/project/best1.png",
    thumbnails: [
      "/project/best1.png",
      "/project/best2.png",
      "/project/best3.png",
      "/project/best4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
  {
    id: 127,
    title: "Welcome to Learn Driving UK",
    description:
      "Local SEO website for a UK driving school targeting learner driver and lesson booking searches across key regions.",
    featured: "/project/learing1.png",
    thumbnails: [
      "/project/learing1.png",
      "/project/learing2.png",
      "/project/learing3.png",
      "/project/learing4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
  {
    id: 128,
    title: "Mini Digger & Driver Hire",
    description:
      "Local SEO project for groundworks and mini digger hire services targeting Bristol, Bath, and surrounding UK areas.",
    featured: "/project/mini1.png",
    thumbnails: [
      "/project/mini1.png",
      "/project/mini2.png",
      "/project/mini3.png",
      "/project/mini4.png",
    ],
    link: "#",
    aos: "fade-right",
    duration: "1000",
    category: "SEO",
  },
];
export const allProjects: Project[] = rawProjects.map(withPaths);
export const projectCategories: string[] = ['All', ...Array.from(new Set(allProjects.map((p) => p.category)))];
